#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)

require "static_site_builder"
require "thor"

DEFAULT_TEMPLATE = StaticSiteBuilder::HTMLTemplater::DEFAULT_TEMPLATE

class SiteBuilderCLI < Thor
  desc "build", "Builds a static HTML website from markdown"
  option :in, default: ".", desc: "Input markdown file dir"
  option :out, default: ".", desc: "Output HTML file dir"
  option(
    :template,
    default: DEFAULT_TEMPLATE,
    desc: "HTML template which embeds the markdown (<body>) of each webpage"
  )
  def build
    template = StaticSiteBuilder::HTMLTemplater.new(
      template_filepath: options[:template],
      gem_included_template: options[:template] == DEFAULT_TEMPLATE
    )

    html_files = StaticSiteBuilder.build_website(
      options[:in],
      template,
      options[:out]
    )

    unless html_files.empty?
      puts "Site built with #{html_files.length} HTML file(s):"
      puts html_files
    else
      puts "No markdown files found in: #{options[:in]}"
    end
  rescue Exception => ex
    puts "An error occurred: #{ex.message}"
  end
end

SiteBuilderCLI.start(ARGV)
